### ISSUE TITLE
前端页面输入框记录

### ISSUE THREAD

**Issue by Becivells** [xiecat/goblin#5]

**Comment by Becivells** [comment]
此模块，作为一个可选功能。大概率会采用前端页面录制。到时候可以实时观看。有开源的解决方案。不用费力去开发 
https://github.com/rrweb-io/rrweb
还有一个也不错，忘记了

**Comment by kkll5875** [comment]
期待更新

**Comment by Becivells** [comment]
因为担心滥用, 此功能砍掉
